### ISSUE TITLE
running markbind returns syntax error

### ISSUE THREAD

**Issue by okkhoy** [MarkBind/markbind-cli#23]
Installed `markbind` using `npm` as suggested in the Quickstart -> Install page.
When I try to run `markbind` I get the following error:

```
anarayan@minibuntu1604:~/Workspace/CS2103/website$ markbind 
/usr/lib/node_modules/markbind-cli/index.js:30
);
^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```
My setup:
```
anarayan@minibuntu1604:~/Workspace/CS2103/website$ npm --version
3.10.10
anarayan@minibuntu1604:~/Workspace/CS2103/website$ node
node    nodejs  
anarayan@minibuntu1604:~/Workspace/CS2103/website$ nodejs --version
v6.12.3
anarayan@minibuntu1604:~/Workspace/CS2103/website$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
anarayan@minibuntu1604:~/Workspace/CS2103/website$ 
```

**Comment by damithc** [comment]
Happened to me too. turns out my node is too old. Reinstalled node (as advised by the dev team) and the error went away.

**Comment by okkhoy** [comment]
What is the suggested `node` version? Install page said `6.5` above; I installed `6.12`

**Comment by damithc** [comment]
We probably need to update the instructions. Current node version is 8.* 
BTW, we updated markbind just a few days ago. That why it needs the latest node. Node 6 was enough for the previous markbind, but not the latest one.

**Comment by acjh** [comment]
Thanks for the feedback! I've updated the [Installation](https://github.com/MarkBind/markbind-cli/wiki/User-Quick-Start#installation) and [Developer Environment](https://github.com/MarkBind/markbind-cli/wiki/Developer-Guide#environment) sections.

> [v1.4.3](https://github.com/MarkBind/markbind-cli/releases/tag/v1.4.3) and above: Node.js with version 8.0 or higher is required.

**Comment by okkhoy** [comment]
Works with Node.js 8.9; I will close this issue
